### ISSUE TITLE
Typo in the audioserver key name (skillserver instead)

### ISSUE THREAD

**Issue by cpoisson** [oziee/AIhome#1]
https://github.com/oziee/AIhome/blob/5801c76ad0514d494c33cd0d8616bce163474678/api/services.py#L68

```
status['skillserver'] = 1
```

should be 

```
status['audioserver'] = 1
```

**Comment by oziee** [comment]
dam copy and paste.. plus I don't run the audio-server on the server side so i never noticed :)

fixed
